from tkinter import *
from tkinter import ttk
root = Tk()
l =ttk.Label(root, text="Starting...")
l.grid()
l.bind('<Enter>', lambda e: l.configure(text='Moved mouse inside'))
l.bind('<Leave>', lambda e: l.configure(text='Moved mouse outside'))
l.bind('<1>', lambda e: l.configure(text='Clicked left mouse button'))
l.bind('<Double-1>', lambda e: l.configure(text='Double clicked'))
l.bind('<B3-Motion>', lambda e: l.configure(text='right button drag to %d,%d' % (e.x, e.y)))
root.mainloop()

'''
Actions are bound to events by resources (e.g. keyword argument
command) or with the method
bind.
bind(self, sequence=None, func=None, add=None)
Bind to this widget at event SEQUENCE a call to function FUNC.
 
            SEQUENCE is a string of concatenated event
            patterns. An event pattern is of the form
            <MODIFIER-MODIFIER-TYPE-DETAIL>
            where MODIFIER is one of Control, Mod2, M2, Shift, Mod3, M3, Lock, Mod4, M4,
            Button1, B1, Mod5, M5 Button2, B2, Meta, M, Button3,
            B3, Alt, Button4, B4, Double, Button5, B5 Triple,
            Mod1, M1.

            TYPE is one of Activate, Enter, Map,
            ButtonPress, Button, Expose, Motion, ButtonRelease
            FocusIn, MouseWheel, Circulate, FocusOut, Property,
            Colormap, Gravity Reparent, Configure, KeyPress, Key,
            Unmap, Deactivate, KeyRelease Visibility, Destroy,
            Leave and DETAIL is the button number for ButtonPress,
            ButtonRelease and DETAIL is the Keysym for KeyPress and
            KeyRelease.

            Examples are
            <Control-Button-1> for pressing Control and mouse button 1 or
            <Alt-A> for pressing A and the Alt key (KeyPress can be omitted).
            An event pattern can also be a virtual event of the form
            <<AString>> where AString can be arbitrary. This
            event can be generated by event_generate.
'''
